[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
magice = "6bQk3gRYVTWG9rKXKcK9Qnj3a9kozXsAWgMixFXt1yKs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn tsx --test --test-reporter=spec tests/*.ts"
